version: "3.7"

services:
  bot:
    build:
      context: .
    working_dir: /app
    command: "python main.py"
    env_file:
      - .env
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure

