version: "3.7"

services:
  bot:
    build:
      context: .
    working_dir: /app/
    command: sh -c "alembic upgrade head && cd src && python -m dayz.bot.bot"

    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure

  db:
    image: postgres:latest
    command: postgres -c 'max_connections=999'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql-data-test:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  admin_panel:
    build:
      context: .
    working_dir: /app/src
    command: "uvicorn dayz.admin_panel.app:app --host 0.0.0.0 --port 5637;"
    env_file:
      - .env
    depends_on:
      - db
      - bot
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    ports:
      - "5637:5637"


volumes:
  postgresql-data-test: