version: "3.7"

services:
  bot:
    build:
      context: .
    working_dir: /app
    command: "python main.py"
    env_file:
      - .env
    environment:
      - TZ=$(cat /etc/timezone)
    volumes:
      - .:/app
    restart: on-failure

