name: deploy

on:
  push:
    branches:
      - main

jobs:  
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }} 
          username: ${{ secrets.REMOTE_FORTUHOST_USERNAME }}
          password: ${{ secrets.REMOTE_FORTUHOST_PASSWORD }}
          script: |
            cd ${{ secrets.COMPOSE_PATH }}
            git pull
            docker-compose up --build -d

      - name: Rollback commit on error
        if: steps.deployment.outcome != 'success'
        run: git reset HEAD
